language: rust
cache: cargo
os:
  - linux
  - osx
script:
  - cargo build --verbose
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
  fast_finish: true