[package]
name = "nimtool"
version = "0.1.0"
authors = ["David Wagner <cptnwinky@gmail.com>"]

[dependencies]
reqwest = "0.8.6"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "1.0.22"
serde_yaml = "0.7.5"
chrono = "0.4.4"
clap = {version = "2.32.0", features = ["yaml", "suggestions", "wrap_help"]}
